apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weather-pod
  namespace: default
spec:
  interval: 5m   # Specify the reconciliation interval (e.g., every 5 minutes)
  releaseName: weather-pod
  chart:
    spec:
      chart: weather-pod
      version: 0.1.0
  values:
    replicaCount: 2
    image:
      repository: nishant2081/k123s
      pullPolicy: IfNotPresent
      tag: "latest"
      sourceRef:
        kind: HelmRepository
        name: weatherapp
        namespace: flux-system
