apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weather-pod
  namespace: default
spec:
  interval: 5m   # Specify the reconciliation interval (e.g., every 5 minutes)
  releaseName: weather-pod
  chart:
    spec:
      chart: weather-pod
      sourceRef:
        kind: HelmRepository
        name: demoproject/weatherapp
        namespace: flux-system
  values:
